name = "safty-tq"
type = "javascript"

[build]
command = "npm run build"
[build.environment]
node_version = "20.14.0"

[site]
bucket = "./dist"
entry-point = "."

[env.production]
pages_build_output_dir = "dist"
